name: annorxiver
channels:
  - conda-forge
dependencies:
  - pip=20.3.3
  - python=3.7.2
  - pip:
    - black==20.8b1
    - CairoSVG==2.4.2
    - flake8==3.8.4
    - gensim==3.8.1
    - habanero==0.7.2
    - jupyter==1.0.0
    - jupyter_client==5.3.4
    - jupyter_console==6.0.0
    - jupyter_core==4.6.0
    - jupytext==1.9.1
    - ipykernel==5.1.2
    - lifelines==0.25.6
    - lxml==4.4.1
    - matplotlib==3.1.1
    - mizani==0.7.2
    - numpy==1.17.5
    - pandas==1.1.4
    - pdfminer==20191125
    - plotnine==0.7.1
    - pre_commit==2.9.3
    - ratelimit==2.2.1
    - requests==2.22.0
    - rpy2==3.3.5
    - sqlalchemy==1.3.13
    - tensorflow==1.15.2
    - tqdm==4.35.0
    - seaborn==0.11.0
    - spacy==2.2.3
    - svgutils==0.3.1
    - umap-learn==0.3.10
    - wordcloud==1.5.0
